include_configs:
  - ../../train/diffusion/diffusion_16x16x16_dense.yaml
  - chair.yaml

name: 'shapenet/chair_diffusion_dense'

vae_config: "configs/shapenet/chair/train_vae_16x16x16_dense.yaml"
vae_checkpoint: "checkpoints/chair/coarse_vae/last.ckpt"