include_configs:
  - ../../train/diffusion/diffusion_16x16x16_dense.yaml
  - car.yaml

name: 'shapenet/car_diffusion_dense'

vae_config: "configs/shapenet/car/train_vae_16x16x16_dense.yaml"
vae_checkpoint: "checkpoints/car/coarse_vae/last.ckpt"