name: point2mesh
channels:
  - pytorch
  - defaults
  - conda-forge
  - fvcore
  - pytorch3d
dependencies:
  - python=3.8.2
  - numpy
  - pytorch==1.12.1 
  - torchvision==0.13.1 
  - cudatoolkit=10.2
  - fvcore
  - pytorch3d
  - pip
  - pip:
    - pytest
    - open3d
