package:
  name: manifold
  version: 0.0.1

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip3 install .

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - pybind11 >=2.10.0

  run:
    - python